# Generated by Django 4.2.3 on 2023-07-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_timemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=25)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='TicketModl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('profileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.profilemodel')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.timemodel')),
            ],
        ),
    ]
