# Generated by Django 4.2.3 on 2023-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_profilemodel_ticketmodl'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='eventImages/'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='profileImages/'),
        ),
        migrations.AddField(
            model_name='ticketmodl',
            name='TicketImage',
            field=models.ImageField(null=True, upload_to='ticketImages/'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='address',
            field=models.CharField(default='karaj-milad', max_length=150),
        ),
    ]
