# Generated by Django 4.2.3 on 2023-09-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ticketing', '0004_eventmodel_poster_profilemodel_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodl',
            name='profileModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilemodel'),
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
